# version: '3'
services:
  # gateway:
  #   build: ./gateway-graphql
  #   container_name: gateway-container
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - event-service
  #     - user-service
  #     - notification-service

  # event-service:
  #   build: ./event-service-kotlin
  #   container_name: event-service-container
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - DB_URL=${DB_URL}
  
  user-service:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: user-service-container
    working_dir: /usr/src/app
    command: "npm start"
    expose:
      - 5011
    ports:
      - "5011:5011"
    # environment:
    #   - DB_URL=${DB_URL}
    # depends_on:
    #   - mongodb

  # storage-service:
  #   restart: always
  #   build: 
  #     context: ./storage_temp
  #     dockerfile: Dockerfile
  #   container_name: storage-service-container
  #   working_dir: /usr/src/app
  #   command: "npm start"
  #   expose:
  #     - 5011
  #   ports:
  #     - "5011:5011"

  # notification-service:
  #   build: ./notification-service-nodejs
  #   container_name: notification-service-container
  #   ports:
  #     - "5003:5003"
  #   depends_on:
  #     - redis

  # mongodb-user-service-nodejs:
  #   image: mongo
  #   container_name: mongodb-container-user-service-nodejs
  #   ports:
  #     - "27018:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  # mongodb-event-service-kotlin:
  #   image: mongo
  #   container_name: mongodb-container-event-service-kotlin
  #   ports:
  #     - "27019:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  # mongodb-notification-service-nodejs:
  #   image: mongo
  #   container_name: mongodb-container-notification-service-nodejs
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  

  # mongodb-gateway-graphql:
  #   image: mongo
  #   container_name: mongodb-container-gateway-graphql
  #   ports:
  #     - "27016:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  

    # redis:
  #   image: redis
  #   container_name: redis-container
  #   ports:
  #     - "6379:6379"

# Use MongoDB Atlas connection string in the .env file for DB_URL

# testando